import { updateDocsTopic, deleteDocsTopic } from "@/lib/server/actions";
import React, { useState } from "react";
import { useTranslation } from "react-i18next";

interface DocsTopicEditProps {
  topicData: {
    id: string;
    title: string;
    slug: string;
    is_hidden: boolean;
  };
  onSave: () => void;
  onDelete: () => void;
  onError?: (message: string) => void;
}

const DocsTopicEdit = ({
  topicData,
  onSave,
  onDelete,
  onError,
}: DocsTopicEditProps) => {
  const { t } = useTranslation();

  const [title, setTitle] = useState(topicData.title);
  const [isHidden, setIsHidden] = useState(topicData.is_hidden);
  const [errors, setErrors] = useState({
    title: "",
  });
  const [submitError, setSubmitError] = useState("");
  const [loading, setLoading] = useState(false);
  const [deleting, setDeleting] = useState(false);

  const handleSave = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    setErrors({ title: "" });
    setSubmitError("");

    if (!title || title.trim().length === 0) {
      setErrors({
        title: t("docs_topic_title_required"),
      });
      setLoading(false);
      return;
    }
    if (title.trim().length > 200) {
      setErrors({
        title: t("docs_title_max_200"),
      });
      setLoading(false);
      return;
    }

    try {
      await updateDocsTopic(topicData.id, title.trim(), isHidden);
      onSave();
    } catch (error) {
      console.error("Failed to update topic:", error);
      const errorMessage =
        error instanceof Error ? error.message : t("docs_topic_update_failed");
      setSubmitError(errorMessage);
      onError?.(errorMessage);
    } finally {
      setLoading(false);
    }
  };

  const handleDelete = async () => {
    const confirmed = window.confirm(
      t("delete_topic_confirm") ||
        "Are you sure you want to delete this topic? All sections within this topic will also be deleted. This action cannot be undone.",
    );

    if (!confirmed) return;

    setDeleting(true);
    setSubmitError("");
    try {
      await deleteDocsTopic(topicData.id);
      onDelete();
    } catch (error) {
      console.error("Failed to delete topic:", error);
      const errorMessage =
        error instanceof Error ? error.message : t("docs_topic_delete_failed");
      setSubmitError(errorMessage);
      onError?.(errorMessage);
      setDeleting(false);
    }
  };

  return (
    <div className="flex flex-col gap-4 w-full p-3 pt-5">
      <span className="text-lg font-bold">{t("edit_topic")}</span>

      <form
        onSubmit={handleSave}
        className="flex flex-col gap-5 w-full max-w-xl"
      >
        {submitError && (
          <div className="alert alert-error text-sm">{submitError}</div>
        )}

        <fieldset className="fieldset">
          <legend className="fieldset-legend">{t("title")}</legend>
          <input
            type="text"
            className="input input-bordered input-md"
            placeholder={t("docs_topic_title_placeholder")}
            value={title}
            onChange={(e) => setTitle(e.target.value)}
            maxLength={200}
          />
          {errors.title && (
            <span className="text-xs text-red-500">{errors.title}</span>
          )}
          <span className="text-xs opacity-60 mt-1">
            {t("docs_slug_autogenerated")}
          </span>
        </fieldset>

        <div className="mt-6 mb-4">
          <button
            type="button"
            className="btn btn-sm"
            onClick={() => setIsHidden(!isHidden)}
            disabled={loading || deleting}
          >
            <div className="inline-grid *:[grid-area:1/1]">
              <div
                className={`status ${
                  !isHidden ? "status-primary" : "status-error"
                } animate-ping`}
              />
              <div
                className={`status ${
                  !isHidden ? "status-primary" : "status-error"
                }`}
              />
            </div>
            {!isHidden ? t("visible") || "Visible" : t("hidden") || "Hidden"}
          </button>
        </div>

        <div className="flex items-center gap-3 mt-2">
          <button
            type="submit"
            className="btn btn-primary w-26"
            disabled={loading || deleting}
          >
            {loading ? t("saving") : t("save")}
          </button>
          <button
            type="button"
            onClick={handleDelete}
            className="btn btn-error ml-auto w-26"
            disabled={loading || deleting}
          >
            {deleting ? t("deleting") : t("delete")}
          </button>
        </div>
      </form>
    </div>
  );
};

export default DocsTopicEdit;
