import { updateDocsSection, deleteDocsSection } from "@/lib/server/actions";
import React, { useState } from "react";
import { useTranslation } from "react-i18next";

interface DocsSectionEditProps {
  sectionData: {
    id: string;
    topic_id: string;
    title: string;
    slug: string;
    description: string;
    is_hidden: boolean;
  };
  onSave: () => void;
  onDelete: () => void;
  onError?: (message: string) => void;
}

const DocsSectionEdit = ({
  sectionData,
  onSave,
  onDelete,
  onError,
}: DocsSectionEditProps) => {
  const { t } = useTranslation();

  const [title, setTitle] = useState(sectionData.title);
  const [description, setDescription] = useState(sectionData.description);
  const [isHidden, setIsHidden] = useState(sectionData.is_hidden);
  const [errors, setErrors] = useState({
    title: "",
    description: "",
  });
  const [submitError, setSubmitError] = useState("");
  const [loading, setLoading] = useState(false);
  const [deleting, setDeleting] = useState(false);

  const handleSave = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    setErrors({ title: "", description: "" });
    setSubmitError("");

    if (!title || title.trim().length === 0) {
      setErrors((prev) => ({
        ...prev,
        title: t("docs_section_title_required"),
      }));
      setLoading(false);
      return;
    }

    if (!description || description.trim().length === 0) {
      setErrors((prev) => ({
        ...prev,
        description: t("docs_section_description_required"),
      }));
      setLoading(false);
      return;
    }

    if (title.trim().length > 200) {
      setErrors((prev) => ({
        ...prev,
        title: t("docs_title_max_200"),
      }));
      setLoading(false);
      return;
    }

    if (description.trim().length > 500) {
      setErrors((prev) => ({
        ...prev,
        description: t("docs_description_max_500"),
      }));
      setLoading(false);
      return;
    }

    try {
      await updateDocsSection(
        sectionData.id,
        title.trim(),
        description.trim(),
        isHidden,
      );
      onSave();
    } catch (error) {
      console.error("Failed to update section:", error);
      const errorMessage =
        error instanceof Error
          ? error.message
          : t("docs_section_update_failed");
      setSubmitError(errorMessage);
      onError?.(errorMessage);
    } finally {
      setLoading(false);
    }
  };

  const handleDelete = async () => {
    const confirmed = window.confirm(
      t("delete_section_confirm") ||
        "Are you sure you want to delete this section? This action cannot be undone.",
    );

    if (!confirmed) return;

    setDeleting(true);
    setSubmitError("");
    try {
      await deleteDocsSection(sectionData.id);
      onDelete();
    } catch (error) {
      console.error("Failed to delete section:", error);
      const errorMessage =
        error instanceof Error
          ? error.message
          : t("docs_section_delete_failed");
      setSubmitError(errorMessage);
      onError?.(errorMessage);
      setDeleting(false);
    }
  };

  return (
    <div className="flex flex-col gap-4 w-full p-3 pt-5">
      <span className="text-lg font-bold">{t("edit_section")}</span>

      <form
        onSubmit={handleSave}
        className="flex flex-col gap-5 w-full max-w-xl"
      >
        {submitError && (
          <div className="alert alert-error text-sm">{submitError}</div>
        )}

        <fieldset className="fieldset">
          <legend className="fieldset-legend">{t("title")}</legend>
          <input
            type="text"
            className="input input-bordered input-md"
            placeholder={t("docs_section_title_placeholder")}
            value={title}
            onChange={(e) => setTitle(e.target.value)}
            maxLength={200}
          />
          {errors.title && (
            <span className="text-xs text-red-500">{errors.title}</span>
          )}
          <span className="text-xs opacity-60 mt-1">
            {t("docs_slug_autogenerated")}
          </span>
        </fieldset>

        <fieldset className="fieldset">
          <legend className="fieldset-legend">{t("description")}</legend>
          <textarea
            className="textarea textarea-bordered min-h-28"
            placeholder={t("docs_section_description_placeholder")}
            value={description}
            onChange={(e) => setDescription(e.target.value)}
            maxLength={500}
          />
          {errors.description && (
            <span className="text-xs text-red-500">{errors.description}</span>
          )}
        </fieldset>

        <div className="mt-6 mb-4">
          <button
            type="button"
            className="btn btn-sm"
            onClick={() => setIsHidden(!isHidden)}
            disabled={loading || deleting}
          >
            <div className="inline-grid *:[grid-area:1/1]">
              <div
                className={`status ${
                  !isHidden ? "status-primary" : "status-error"
                } animate-ping`}
              />
              <div
                className={`status ${
                  !isHidden ? "status-primary" : "status-error"
                }`}
              />
            </div>
            {!isHidden ? t("visible") || "Visible" : t("hidden") || "Hidden"}
          </button>
        </div>

        <div className="flex items-center gap-3 mt-2">
          <button
            type="submit"
            className="btn btn-primary w-26"
            disabled={loading || deleting}
          >
            {loading ? t("saving") : t("save")}
          </button>
          <button
            type="button"
            onClick={handleDelete}
            className="btn btn-error ml-auto w-26"
            disabled={loading || deleting}
          >
            {deleting ? t("deleting") : t("delete")}
          </button>
        </div>
      </form>
    </div>
  );
};

export default DocsSectionEdit;
