import { createDocsSection } from "@/lib/server/actions";
import React, { useState } from "react";
import { useTranslation } from "react-i18next";

interface DocsSectionCreateProps {
  topicId: string;
  onSave: () => void;
  onError?: (message: string) => void;
}

const DocsSectionCreate = ({
  topicId,
  onSave,
  onError,
}: DocsSectionCreateProps) => {
  const { t } = useTranslation();

  const [title, setTitle] = useState("");
  const [description, setDescription] = useState("");
  const [errors, setErrors] = useState({
    title: "",
    description: "",
  });
  const [submitError, setSubmitError] = useState("");
  const [loading, setLoading] = useState(false);

  const handleSave = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    setErrors({ title: "", description: "" });
    setSubmitError("");

    if (!title || title.trim().length === 0) {
      setErrors((prev) => ({
        ...prev,
        title: t("docs_section_title_required"),
      }));
      setLoading(false);
      return;
    }

    if (!description || description.trim().length === 0) {
      setErrors((prev) => ({
        ...prev,
        description: t("docs_section_description_required"),
      }));
      setLoading(false);
      return;
    }

    if (title.trim().length > 200) {
      setErrors((prev) => ({
        ...prev,
        title: t("docs_title_max_200"),
      }));
      setLoading(false);
      return;
    }

    if (description.trim().length > 500) {
      setErrors((prev) => ({
        ...prev,
        description: t("docs_description_max_500"),
      }));
      setLoading(false);
      return;
    }

    try {
      await createDocsSection(topicId, title.trim(), description.trim());
      setTitle("");
      setDescription("");
      setErrors({ title: "", description: "" });
      setSubmitError("");
      onSave();
    } catch (error) {
      console.error("Failed to create section:", error);
      const errorMessage =
        error instanceof Error
          ? error.message
          : t("docs_section_create_failed");
      setSubmitError(errorMessage);
      onError?.(errorMessage);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="flex flex-col gap-4 w-full p-3 pt-5">
      <span className="text-lg font-bold">{t("create_section")}</span>

      <form
        onSubmit={handleSave}
        className="flex flex-col gap-5 w-full max-w-xl"
      >
        {submitError && (
          <div className="alert alert-error text-sm">{submitError}</div>
        )}

        <fieldset className="fieldset">
          <legend className="fieldset-legend">{t("title")}</legend>
          <input
            type="text"
            className="input input-bordered input-md"
            placeholder={t("docs_section_title_placeholder")}
            value={title}
            onChange={(e) => setTitle(e.target.value)}
            maxLength={200}
          />
          {errors.title && (
            <span className="text-xs text-red-500">{errors.title}</span>
          )}
          <span className="text-xs opacity-60 mt-1">
            {t("docs_slug_autogenerated")}
          </span>
        </fieldset>

        <fieldset className="fieldset">
          <legend className="fieldset-legend">{t("description")}</legend>
          <textarea
            className="textarea textarea-bordered min-h-28"
            placeholder={t("docs_section_description_placeholder")}
            value={description}
            onChange={(e) => setDescription(e.target.value)}
            maxLength={500}
          />
          {errors.description && (
            <span className="text-xs text-red-500">{errors.description}</span>
          )}
        </fieldset>

        <div className="flex items-center gap-3 mt-2">
          <button
            type="submit"
            className="btn btn-primary w-36"
            disabled={loading}
          >
            {loading ? t("creating") : t("create_section")}
          </button>
        </div>
      </form>
    </div>
  );
};

export default DocsSectionCreate;
