import { createDocsTopic } from "@/lib/server/actions";
import React, { useState } from "react";
import { useTranslation } from "react-i18next";

interface DocsTopicCreateProps {
  onSave: () => void;
  onError?: (message: string) => void;
}

const DocsTopicCreate = ({ onSave, onError }: DocsTopicCreateProps) => {
  const { t } = useTranslation();

  const [title, setTitle] = useState("");
  const [errors, setErrors] = useState({
    title: "",
  });
  const [submitError, setSubmitError] = useState("");
  const [loading, setLoading] = useState(false);

  const handleSave = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    setErrors({ title: "" });
    setSubmitError("");

    if (!title || title.trim().length === 0) {
      setErrors({
        title: t("docs_topic_title_required"),
      });
      setLoading(false);
      return;
    }
    if (title.trim().length > 200) {
      setErrors({
        title: t("docs_title_max_200"),
      });
      setLoading(false);
      return;
    }

    try {
      await createDocsTopic(title.trim());
      setTitle("");
      setErrors({ title: "" });
      setSubmitError("");
      onSave();
    } catch (error) {
      console.error("Failed to create topic:", error);
      const errorMessage =
        error instanceof Error ? error.message : t("docs_topic_create_failed");
      setSubmitError(errorMessage);
      onError?.(errorMessage);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="flex flex-col gap-4 w-full p-3 pt-5">
      <span className="text-lg font-bold">{t("create_topic")}</span>

      <form
        onSubmit={handleSave}
        className="flex flex-col gap-5 w-full max-w-xl"
      >
        {submitError && (
          <div className="alert alert-error text-sm">{submitError}</div>
        )}

        <fieldset className="fieldset">
          <legend className="fieldset-legend">{t("title")}</legend>
          <input
            type="text"
            className="input input-bordered input-md"
            placeholder={t("docs_topic_title_placeholder")}
            value={title}
            onChange={(e) => setTitle(e.target.value)}
            maxLength={200}
          />
          {errors.title && (
            <span className="text-xs text-red-500">{errors.title}</span>
          )}
          <span className="text-xs opacity-60 mt-1">
            {t("docs_slug_autogenerated")}
          </span>
        </fieldset>

        <div>
          <button
            type="submit"
            className="btn btn-primary mt-2 w-36"
            disabled={loading}
          >
            {loading ? t("creating") : t("create_topic")}
          </button>
        </div>
      </form>
    </div>
  );
};

export default DocsTopicCreate;
